const { expectRevert } = require("@openzeppelin/test-helpers");
const { web3 } = require("@openzeppelin/test-helpers/src/setup");
// Import mock ERC20 tokens.
const Dai = artifacts.require("mocks/Dai.sol");
const Bat = artifacts.require("mocks/Bat.sol");
const Rep = artifacts.require("mocks/Rep.sol");
const Zrx = artifacts.require("mocks/Zrx.sol");

const SIDE = {
  BUY: 0,
  SELL: 1,
};

// Import contract abstraction of the Decentralized Exchange
const Dex = artifacts.require("Dex.sol");

// Create byte32 variables using web3 for ticker argument
const [DAI, BAT, REP, ZRX] = ["DAI", "BAT", "REP", "ZRX"].map((ticker) =>
  web3.utils.fromAscii(ticker)
);

// Define cotract block to write tests.
contract("Dex", (accounts) => {
  // accounts --> list of addresses generated by local development blockchain.
  // Variables pointing to ERC20 tokens.
  let dai, bat, rep, zrx, dex;

  const [trader1, trader2] = [accounts[1], accounts[2]];
  // We start with accounts[1] because accounts[0] is admin.

  // Deploy tokens in a before-each hook (Runs before each test).
  beforeEach(async () => {
    [dai, bat, rep, zrx] = await Promise.all([
      // Returns an array of four contract instances,
      // Stored one in each variable by 'Array Destructuring'.
      Dai.new(),
      Bat.new(),
      Rep.new(),
      Zrx.new(),
    ]);
    dex = await Dex.new(); // Deploy Dex smart contract.
    // Configure ERC20 tokens in the Dex (Call addToken for each token)
    await Promise.all([
      dex.addToken(DAI, dai.address),
      dex.addToken(BAT, bat.address),
      dex.addToken(REP, rep.address),
      dex.addToken(ZRX, zrx.address),
    ]);

    // Specify the initial token amount.
    const amount = web3.utils.toWei("1000");

    // Function to allocate ERC20 tokens
    const seedTokenBalance = async (token, trader) => {
      // Allocate token to an address.
      await token.faucet(trader, amount);
      // Trader approves the Dex smart contract to transfer tokens.
      await token.approve(dex.address, amount, { from: trader });
    };

    // Loop through all tokens and call seedTokenBalance function.
    await Promise.all(
      [dai, bat, rep, zrx].map((token) => seedTokenBalance(token, trader1))
    );
    await Promise.all(
      [dai, bat, rep, zrx].map((token) => seedTokenBalance(token, trader2))
    );
  });
  //   Test deposit()----Happy Path
  it("should deposit tokens", async () => {
    const amount = web3.utils.toWei("100");

    await dex.deposit(amount, DAI, { from: trader1 });
    const balance = await dex.traderBalances(trader1, DAI);
    assert(balance.toString() === amount);
  });
  // Test deposit()---Unhappy Path
  it("should NOT deposit token if token does not exist", async () => {
    await expectRevert(
      dex.deposit(
        web3.utils.toWei("100"),
        web3.utils.fromAscii("TOKEN-DOES-NOT-EXIST"),
        { from: trader1 }
      ),
      "Token does not exist!"
    );
  });
  // Test withdraw()---Happy Path
  it("Should withdraw tokens", async () => {
    const amount = web3.utils.toWei("100");

    await dex.deposit(amount, DAI, { from: trader1 });

    await dex.withdraw(amount, DAI, { from: trader1 });

    const [balanceDex, balanceDai] = await Promise.all([
      dex.traderBalances(trader1, DAI),
      dai.balanceOf(trader1),
    ]);

    assert(balanceDex.isZero());
    assert(balanceDai.toString() === web3.utils.toWei("1000"));
  });
  // Test withdraw()---Unhappy Path
  it("Should NOT withdraw tokens if token does not exist", async () => {
    await expectRevert(
      dex.withdraw(
        web3.utils.toWei("100"),
        web3.utils.fromAscii("Token-does-not-exist"),
        { from: trader1 }
      ),
      "Token does not exist!"
    );
  });
  it("Should NOT withdraw tokens if balance is too low", async () => {
    await dex.deposit(web3.utils.toWei("100"), DAI, { from: trader1 });
    await expectRevert(
      dex.withdraw(web3.utils.toWei("1000"), DAI, { from: trader1 }),
      "Balance too low!"
    );
  });

  // Test createLimitOrder()---Happy Path
  it("Should create limit order", async () => {
    //Add 100 DAI to the smart contract
    await dex.deposit(web3.utils.toWei("100"), DAI, { from: trader1 });

    await dex.createLimitOrder(REP, web3.utils.toWei("10"), 10, SIDE.BUY, {
      from: trader1,
    });
    // Inspect the orderbook and find our order
    let buyOrders = await dex.getOrders(REP, SIDE.BUY);
    let sellOrders = await dex.getOrders(REP, SIDE.SELL);
    assert(buyOrders.length === 1);
    assert(buyOrders[0].trader === trader1);
    assert(buyOrders[0].ticker === web3.utils.padRight(REP, 64));
    assert(buyOrders[0].price === "10");
    assert(buyOrders[0].amount === web3.utils.toWei("10"));
    assert(sellOrders.length === 0);

    await dex.deposit(web3.utils.toWei("200"), DAI, { from: trader2 });

    await dex.createLimitOrder(REP, web3.utils.toWei("10"), 11, SIDE.BUY, {
      from: trader2,
    });
    buyOrders = await dex.getOrders(REP, SIDE.BUY);
    sellOrders = await dex.getOrders(REP, SIDE.SELL);
    assert(buyOrders.length === 2);
    assert(buyOrders[0].trader === trader2); //Higher price should appear first
    assert(buyOrders[1].trader === trader1);
    assert(sellOrders.length === 0);

    await dex.createLimitOrder(REP, web3.utils.toWei("10"), 9, SIDE.BUY, {
      from: trader2,
    });
    buyOrders = await dex.getOrders(REP, SIDE.BUY);
    sellOrders = await dex.getOrders(REP, SIDE.SELL);
    assert(buyOrders.length === 3);
    assert(buyOrders[0].trader === trader2);
    assert(buyOrders[1].trader === trader1);
    assert(buyOrders[2].trader === trader2);
    assert(buyOrders[2].price === "9");
    assert(sellOrders.length === 0);
  });

  // Test createLimitOrder()---Unhappy Path
  it("Should not create limit order if token does not exist", async () => {
    await expectRevert(
      dex.createLimitOrder(
        web3.utils.fromAscii("TOKEN-DOES-NOT-EXOST"),
        web3.utils.toWei("1000"),
        10,
        SIDE.BUY,
        { from: trader1 }
      ),
      "Token does not exist!"
    );
  });
  it("Should not create limit order if token is DAI", async () => {
    await expectRevert(
      dex.createLimitOrder(DAI, web3.utils.toWei("1000"), 10, SIDE.BUY, {
        from: trader1,
      }),
      "Can not trade DAI"
    );
  });
  it("Should not create limit order if token balance is too low", async () => {
    await dex.deposit(web3.utils.toWei("99"), REP, { from: trader1 });
    await expectRevert(
      dex.createLimitOrder(REP, web3.utils.toWei("100"), 10, SIDE.SELL, {
        from: trader1,
      }),
      "token balance too low"
    );
  });
  it("Should not create limit order if dai balance is too low", async () => {
    await dex.deposit(web3.utils.toWei("99"), DAI, { from: trader1 });
    await expectRevert(
      dex.createLimitOrder(REP, web3.utils.toWei("10"), 10, SIDE.BUY, {
        from: trader1,
      }),
      "dai balance too low"
    );
  });
  // Test createMarketOrder()---Happy Path
  it("Should create market order and match against existing limit order", async () => {
    await dex.deposit(web3.utils.toWei("100"), DAI, { from: trader1 });
    await dex.createLimitOrder(REP, web3.utils.toWei("10"), 10, SIDE.BUY, {
      from: trader1,
    });
    await dex.deposit(web3.utils.toWei("100"), REP, { from: trader2 });
    await dex.createMarketOrder(REP, web3.utils.toWei("5"), SIDE.SELL, {
      from: trader2,
    });
    const balances = await Promise.all([
      dex.traderBalances(trader1, DAI),
      dex.traderBalances(trader1, REP),
      dex.traderBalances(trader2, DAI),
      dex.traderBalances(trader2, REP),
    ]);
    const orders = await dex.getOrders(REP, SIDE.BUY);
    assert(orders.length === 1);
    assert(orders[0].filled === web3.utils.toWei("5"));
    assert(balances[0].toString() === web3.utils.toWei("50"));
    assert(balances[1].toString() === web3.utils.toWei("5"));
    assert(balances[2].toString() === web3.utils.toWei("50"));
    assert(balances[3].toString() === web3.utils.toWei("95"));
  });
  // Test createMarketOrder()---Unhappy Path
  it("Should not create market order if token does not exist", async () => {
    await expectRevert(
      dex.createMarketOrder(
        web3.utils.fromAscii("TOKEN-DOES-NOT-EXOST"),
        web3.utils.toWei("1000"),
        SIDE.BUY,
        { from: trader1 }
      ),
      "Token does not exist!"
    );
  });
  it("Should not create market order if token is DAI", async () => {
    await expectRevert(
      dex.createMarketOrder(DAI, web3.utils.toWei("1000"), SIDE.BUY, {
        from: trader1,
      }),
      "Can not trade DAI"
    );
  });
  it("Should not create market order if token balance is too low", async () => {
    await dex.deposit(web3.utils.toWei("99"), REP, { from: trader1 });
    await expectRevert(
      dex.createMarketOrder(REP, web3.utils.toWei("100"), SIDE.SELL, {
        from: trader1,
      }),
      "token balance too low"
    );
  });
  it("Should not create market order if DAI balance is too low", async () => {
    await dex.deposit(web3.utils.toWei("100"), REP, { from: trader1 });
    await dex.createLimitOrder(REP, web3.utils.toWei("100"), 10, SIDE.SELL, {
      from: trader1,
    });
    await expectRevert(
      dex.createMarketOrder(REP, web3.utils.toWei("100"), SIDE.BUY, {
        from: trader2,
      }),
      "dai balance too low"
    );
  });
});
